// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/capman/internal/common.proto

package io.capman.proto.internal;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(io.capman.proto.internal.Common.serviceType);
    registry.add(io.capman.proto.internal.Common.defaultServiceUriParams);
    registry.add(io.capman.proto.internal.Common.defaultClientUriParams);
    registry.add(io.capman.proto.internal.Common.defaultClusterStrategy);
    registry.add(io.capman.proto.internal.Common.defaultLoadBalanceStrategy);
  }
  /**
   * Protobuf enum {@code io.capman.proto.internal.EnumInternalRet}
   */
  public enum EnumInternalRet
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SERIALIZATION_EXCEPTION = -3;</code>
     */
    SERIALIZATION_EXCEPTION(0, -3),
    /**
     * <code>TIMEOUT_EXCEPTION = -2;</code>
     */
    TIMEOUT_EXCEPTION(1, -2),
    /**
     * <code>NETWORK_EXCEPTION = -1;</code>
     */
    NETWORK_EXCEPTION(2, -1),
    /**
     * <code>OK = 200;</code>
     */
    OK(3, 200),
    /**
     * <code>INTERNAL_ERROR = 500;</code>
     */
    INTERNAL_ERROR(4, 500),
    ;

    /**
     * <code>SERIALIZATION_EXCEPTION = -3;</code>
     */
    public static final int SERIALIZATION_EXCEPTION_VALUE = -3;
    /**
     * <code>TIMEOUT_EXCEPTION = -2;</code>
     */
    public static final int TIMEOUT_EXCEPTION_VALUE = -2;
    /**
     * <code>NETWORK_EXCEPTION = -1;</code>
     */
    public static final int NETWORK_EXCEPTION_VALUE = -1;
    /**
     * <code>OK = 200;</code>
     */
    public static final int OK_VALUE = 200;
    /**
     * <code>INTERNAL_ERROR = 500;</code>
     */
    public static final int INTERNAL_ERROR_VALUE = 500;


    public final int getNumber() { return value; }

    public static EnumInternalRet valueOf(int value) {
      switch (value) {
        case -3: return SERIALIZATION_EXCEPTION;
        case -2: return TIMEOUT_EXCEPTION;
        case -1: return NETWORK_EXCEPTION;
        case 200: return OK;
        case 500: return INTERNAL_ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EnumInternalRet>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<EnumInternalRet>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EnumInternalRet>() {
            public EnumInternalRet findValueByNumber(int number) {
              return EnumInternalRet.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.capman.proto.internal.Common.getDescriptor().getEnumTypes().get(0);
    }

    private static final EnumInternalRet[] VALUES = values();

    public static EnumInternalRet valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private EnumInternalRet(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:io.capman.proto.internal.EnumInternalRet)
  }

  /**
   * Protobuf enum {@code io.capman.proto.internal.EServiceType}
   *
   * <pre>
   *服务类型
   * </pre>
   */
  public enum EServiceType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>EServiceType_Any = 0;</code>
     *
     * <pre>
     *任意
     * </pre>
     */
    EServiceType_Any(0, 0),
    /**
     * <code>EServiceType_Logic = 1;</code>
     *
     * <pre>
     *逻辑服务,默认不会保存状态,例如业务逻辑服务
     * </pre>
     */
    EServiceType_Logic(1, 1),
    /**
     * <code>EServiceType_Storage = 2;</code>
     *
     * <pre>
     *存储服务,用于保存状态,例如各种存储服务,队列服务
     * </pre>
     */
    EServiceType_Storage(2, 2),
    ;

    /**
     * <code>EServiceType_Any = 0;</code>
     *
     * <pre>
     *任意
     * </pre>
     */
    public static final int EServiceType_Any_VALUE = 0;
    /**
     * <code>EServiceType_Logic = 1;</code>
     *
     * <pre>
     *逻辑服务,默认不会保存状态,例如业务逻辑服务
     * </pre>
     */
    public static final int EServiceType_Logic_VALUE = 1;
    /**
     * <code>EServiceType_Storage = 2;</code>
     *
     * <pre>
     *存储服务,用于保存状态,例如各种存储服务,队列服务
     * </pre>
     */
    public static final int EServiceType_Storage_VALUE = 2;


    public final int getNumber() { return value; }

    public static EServiceType valueOf(int value) {
      switch (value) {
        case 0: return EServiceType_Any;
        case 1: return EServiceType_Logic;
        case 2: return EServiceType_Storage;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EServiceType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<EServiceType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EServiceType>() {
            public EServiceType findValueByNumber(int number) {
              return EServiceType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.capman.proto.internal.Common.getDescriptor().getEnumTypes().get(1);
    }

    private static final EServiceType[] VALUES = values();

    public static EServiceType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private EServiceType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:io.capman.proto.internal.EServiceType)
  }

  /**
   * Protobuf enum {@code io.capman.proto.internal.EClusterStrategy}
   *
   * <pre>
   *方法扩展
   * </pre>
   */
  public enum EClusterStrategy
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>EClusterStrategy_FailOver = 1;</code>
     *
     * <pre>
     *失败自动切换，当出现失败，重试其它服务器，通常用于读操作（推荐使用）
     * </pre>
     */
    EClusterStrategy_FailOver(0, 1),
    /**
     * <code>EClusterStrategy_FailFast = 2;</code>
     *
     * <pre>
     *快速失败，只发起一次调用，失败立即报错,通常用于非幂等性的写操作
     * </pre>
     */
    EClusterStrategy_FailFast(1, 2),
    /**
     * <code>EClusterStrategy_FailRetry = 3;</code>
     *
     * <pre>
     *失败重试，出现网络异常时，直接重试
     * </pre>
     */
    EClusterStrategy_FailRetry(2, 3),
    /**
     * <code>EClusterStrategy_Custom = 4;</code>
     *
     * <pre>
     *自定义
     * </pre>
     */
    EClusterStrategy_Custom(3, 4),
    ;

    /**
     * <code>EClusterStrategy_FailOver = 1;</code>
     *
     * <pre>
     *失败自动切换，当出现失败，重试其它服务器，通常用于读操作（推荐使用）
     * </pre>
     */
    public static final int EClusterStrategy_FailOver_VALUE = 1;
    /**
     * <code>EClusterStrategy_FailFast = 2;</code>
     *
     * <pre>
     *快速失败，只发起一次调用，失败立即报错,通常用于非幂等性的写操作
     * </pre>
     */
    public static final int EClusterStrategy_FailFast_VALUE = 2;
    /**
     * <code>EClusterStrategy_FailRetry = 3;</code>
     *
     * <pre>
     *失败重试，出现网络异常时，直接重试
     * </pre>
     */
    public static final int EClusterStrategy_FailRetry_VALUE = 3;
    /**
     * <code>EClusterStrategy_Custom = 4;</code>
     *
     * <pre>
     *自定义
     * </pre>
     */
    public static final int EClusterStrategy_Custom_VALUE = 4;


    public final int getNumber() { return value; }

    public static EClusterStrategy valueOf(int value) {
      switch (value) {
        case 1: return EClusterStrategy_FailOver;
        case 2: return EClusterStrategy_FailFast;
        case 3: return EClusterStrategy_FailRetry;
        case 4: return EClusterStrategy_Custom;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EClusterStrategy>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<EClusterStrategy>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EClusterStrategy>() {
            public EClusterStrategy findValueByNumber(int number) {
              return EClusterStrategy.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.capman.proto.internal.Common.getDescriptor().getEnumTypes().get(2);
    }

    private static final EClusterStrategy[] VALUES = values();

    public static EClusterStrategy valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private EClusterStrategy(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:io.capman.proto.internal.EClusterStrategy)
  }

  /**
   * Protobuf enum {@code io.capman.proto.internal.ELoadbalanceStrategy}
   */
  public enum ELoadbalanceStrategy
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ELoadbalanceStrategy_ConsistentHash = 1;</code>
     *
     * <pre>
     *一致性hash
     * </pre>
     */
    ELoadbalanceStrategy_ConsistentHash(0, 1),
    /**
     * <code>ELoadbalanceStrategy_Random = 2;</code>
     *
     * <pre>
     *随机
     * </pre>
     */
    ELoadbalanceStrategy_Random(1, 2),
    /**
     * <code>ELoadbalanceStrategy_RoundRobin = 3;</code>
     *
     * <pre>
     *轮训
     * </pre>
     */
    ELoadbalanceStrategy_RoundRobin(2, 3),
    /**
     * <code>ELoadbalanceStrategy_Custom = 4;</code>
     *
     * <pre>
     *自定义
     * </pre>
     */
    ELoadbalanceStrategy_Custom(3, 4),
    ;

    /**
     * <code>ELoadbalanceStrategy_ConsistentHash = 1;</code>
     *
     * <pre>
     *一致性hash
     * </pre>
     */
    public static final int ELoadbalanceStrategy_ConsistentHash_VALUE = 1;
    /**
     * <code>ELoadbalanceStrategy_Random = 2;</code>
     *
     * <pre>
     *随机
     * </pre>
     */
    public static final int ELoadbalanceStrategy_Random_VALUE = 2;
    /**
     * <code>ELoadbalanceStrategy_RoundRobin = 3;</code>
     *
     * <pre>
     *轮训
     * </pre>
     */
    public static final int ELoadbalanceStrategy_RoundRobin_VALUE = 3;
    /**
     * <code>ELoadbalanceStrategy_Custom = 4;</code>
     *
     * <pre>
     *自定义
     * </pre>
     */
    public static final int ELoadbalanceStrategy_Custom_VALUE = 4;


    public final int getNumber() { return value; }

    public static ELoadbalanceStrategy valueOf(int value) {
      switch (value) {
        case 1: return ELoadbalanceStrategy_ConsistentHash;
        case 2: return ELoadbalanceStrategy_Random;
        case 3: return ELoadbalanceStrategy_RoundRobin;
        case 4: return ELoadbalanceStrategy_Custom;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ELoadbalanceStrategy>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ELoadbalanceStrategy>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ELoadbalanceStrategy>() {
            public ELoadbalanceStrategy findValueByNumber(int number) {
              return ELoadbalanceStrategy.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.capman.proto.internal.Common.getDescriptor().getEnumTypes().get(3);
    }

    private static final ELoadbalanceStrategy[] VALUES = values();

    public static ELoadbalanceStrategy valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ELoadbalanceStrategy(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:io.capman.proto.internal.ELoadbalanceStrategy)
  }

  public interface InternalRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.capman.proto.internal.InternalRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 uin = 1;</code>
     */
    boolean hasUin();
    /**
     * <code>required int64 uin = 1;</code>
     */
    long getUin();

    /**
     * <code>required bytes reqData = 2;</code>
     */
    boolean hasReqData();
    /**
     * <code>required bytes reqData = 2;</code>
     */
    com.google.protobuf.ByteString getReqData();
  }
  /**
   * Protobuf type {@code io.capman.proto.internal.InternalRequest}
   */
  public static final class InternalRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:io.capman.proto.internal.InternalRequest)
      InternalRequestOrBuilder {
    // Use InternalRequest.newBuilder() to construct.
    private InternalRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private InternalRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final InternalRequest defaultInstance;
    public static InternalRequest getDefaultInstance() {
      return defaultInstance;
    }

    public InternalRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private InternalRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              uin_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              reqData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.capman.proto.internal.Common.internal_static_io_capman_proto_internal_InternalRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.capman.proto.internal.Common.internal_static_io_capman_proto_internal_InternalRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.capman.proto.internal.Common.InternalRequest.class, io.capman.proto.internal.Common.InternalRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<InternalRequest> PARSER =
        new com.google.protobuf.AbstractParser<InternalRequest>() {
      public InternalRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InternalRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<InternalRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int UIN_FIELD_NUMBER = 1;
    private long uin_;
    /**
     * <code>required int64 uin = 1;</code>
     */
    public boolean hasUin() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 uin = 1;</code>
     */
    public long getUin() {
      return uin_;
    }

    public static final int REQDATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString reqData_;
    /**
     * <code>required bytes reqData = 2;</code>
     */
    public boolean hasReqData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes reqData = 2;</code>
     */
    public com.google.protobuf.ByteString getReqData() {
      return reqData_;
    }

    private void initFields() {
      uin_ = 0L;
      reqData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUin()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReqData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, uin_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, reqData_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, uin_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, reqData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static io.capman.proto.internal.Common.InternalRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.capman.proto.internal.Common.InternalRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.capman.proto.internal.Common.InternalRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.capman.proto.internal.Common.InternalRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.capman.proto.internal.Common.InternalRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.capman.proto.internal.Common.InternalRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.capman.proto.internal.Common.InternalRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.capman.proto.internal.Common.InternalRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.capman.proto.internal.Common.InternalRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.capman.proto.internal.Common.InternalRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.capman.proto.internal.Common.InternalRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.capman.proto.internal.InternalRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.capman.proto.internal.InternalRequest)
        io.capman.proto.internal.Common.InternalRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.capman.proto.internal.Common.internal_static_io_capman_proto_internal_InternalRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.capman.proto.internal.Common.internal_static_io_capman_proto_internal_InternalRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.capman.proto.internal.Common.InternalRequest.class, io.capman.proto.internal.Common.InternalRequest.Builder.class);
      }

      // Construct using io.capman.proto.internal.Common.InternalRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uin_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        reqData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.capman.proto.internal.Common.internal_static_io_capman_proto_internal_InternalRequest_descriptor;
      }

      public io.capman.proto.internal.Common.InternalRequest getDefaultInstanceForType() {
        return io.capman.proto.internal.Common.InternalRequest.getDefaultInstance();
      }

      public io.capman.proto.internal.Common.InternalRequest build() {
        io.capman.proto.internal.Common.InternalRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.capman.proto.internal.Common.InternalRequest buildPartial() {
        io.capman.proto.internal.Common.InternalRequest result = new io.capman.proto.internal.Common.InternalRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uin_ = uin_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.reqData_ = reqData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.capman.proto.internal.Common.InternalRequest) {
          return mergeFrom((io.capman.proto.internal.Common.InternalRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.capman.proto.internal.Common.InternalRequest other) {
        if (other == io.capman.proto.internal.Common.InternalRequest.getDefaultInstance()) return this;
        if (other.hasUin()) {
          setUin(other.getUin());
        }
        if (other.hasReqData()) {
          setReqData(other.getReqData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUin()) {
          
          return false;
        }
        if (!hasReqData()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.capman.proto.internal.Common.InternalRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.capman.proto.internal.Common.InternalRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long uin_ ;
      /**
       * <code>required int64 uin = 1;</code>
       */
      public boolean hasUin() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 uin = 1;</code>
       */
      public long getUin() {
        return uin_;
      }
      /**
       * <code>required int64 uin = 1;</code>
       */
      public Builder setUin(long value) {
        bitField0_ |= 0x00000001;
        uin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 uin = 1;</code>
       */
      public Builder clearUin() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uin_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString reqData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes reqData = 2;</code>
       */
      public boolean hasReqData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes reqData = 2;</code>
       */
      public com.google.protobuf.ByteString getReqData() {
        return reqData_;
      }
      /**
       * <code>required bytes reqData = 2;</code>
       */
      public Builder setReqData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        reqData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes reqData = 2;</code>
       */
      public Builder clearReqData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        reqData_ = getDefaultInstance().getReqData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:io.capman.proto.internal.InternalRequest)
    }

    static {
      defaultInstance = new InternalRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:io.capman.proto.internal.InternalRequest)
  }

  public interface InternalResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.capman.proto.internal.InternalResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 ret = 1;</code>
     */
    boolean hasRet();
    /**
     * <code>required int32 ret = 1;</code>
     */
    int getRet();

    /**
     * <code>required bytes respData = 2;</code>
     */
    boolean hasRespData();
    /**
     * <code>required bytes respData = 2;</code>
     */
    com.google.protobuf.ByteString getRespData();

    /**
     * <code>optional string msg = 3;</code>
     */
    boolean hasMsg();
    /**
     * <code>optional string msg = 3;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>optional string msg = 3;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * Protobuf type {@code io.capman.proto.internal.InternalResponse}
   */
  public static final class InternalResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:io.capman.proto.internal.InternalResponse)
      InternalResponseOrBuilder {
    // Use InternalResponse.newBuilder() to construct.
    private InternalResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private InternalResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final InternalResponse defaultInstance;
    public static InternalResponse getDefaultInstance() {
      return defaultInstance;
    }

    public InternalResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private InternalResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              ret_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              respData_ = input.readBytes();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              msg_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.capman.proto.internal.Common.internal_static_io_capman_proto_internal_InternalResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.capman.proto.internal.Common.internal_static_io_capman_proto_internal_InternalResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.capman.proto.internal.Common.InternalResponse.class, io.capman.proto.internal.Common.InternalResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<InternalResponse> PARSER =
        new com.google.protobuf.AbstractParser<InternalResponse>() {
      public InternalResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InternalResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<InternalResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RET_FIELD_NUMBER = 1;
    private int ret_;
    /**
     * <code>required int32 ret = 1;</code>
     */
    public boolean hasRet() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 ret = 1;</code>
     */
    public int getRet() {
      return ret_;
    }

    public static final int RESPDATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString respData_;
    /**
     * <code>required bytes respData = 2;</code>
     */
    public boolean hasRespData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes respData = 2;</code>
     */
    public com.google.protobuf.ByteString getRespData() {
      return respData_;
    }

    public static final int MSG_FIELD_NUMBER = 3;
    private java.lang.Object msg_;
    /**
     * <code>optional string msg = 3;</code>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string msg = 3;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msg = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      ret_ = 0;
      respData_ = com.google.protobuf.ByteString.EMPTY;
      msg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRet()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRespData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, ret_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, respData_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, ret_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, respData_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static io.capman.proto.internal.Common.InternalResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.capman.proto.internal.Common.InternalResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.capman.proto.internal.Common.InternalResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.capman.proto.internal.Common.InternalResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.capman.proto.internal.Common.InternalResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.capman.proto.internal.Common.InternalResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.capman.proto.internal.Common.InternalResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.capman.proto.internal.Common.InternalResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.capman.proto.internal.Common.InternalResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.capman.proto.internal.Common.InternalResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.capman.proto.internal.Common.InternalResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.capman.proto.internal.InternalResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.capman.proto.internal.InternalResponse)
        io.capman.proto.internal.Common.InternalResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.capman.proto.internal.Common.internal_static_io_capman_proto_internal_InternalResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.capman.proto.internal.Common.internal_static_io_capman_proto_internal_InternalResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.capman.proto.internal.Common.InternalResponse.class, io.capman.proto.internal.Common.InternalResponse.Builder.class);
      }

      // Construct using io.capman.proto.internal.Common.InternalResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ret_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        respData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.capman.proto.internal.Common.internal_static_io_capman_proto_internal_InternalResponse_descriptor;
      }

      public io.capman.proto.internal.Common.InternalResponse getDefaultInstanceForType() {
        return io.capman.proto.internal.Common.InternalResponse.getDefaultInstance();
      }

      public io.capman.proto.internal.Common.InternalResponse build() {
        io.capman.proto.internal.Common.InternalResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.capman.proto.internal.Common.InternalResponse buildPartial() {
        io.capman.proto.internal.Common.InternalResponse result = new io.capman.proto.internal.Common.InternalResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ret_ = ret_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.respData_ = respData_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.msg_ = msg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.capman.proto.internal.Common.InternalResponse) {
          return mergeFrom((io.capman.proto.internal.Common.InternalResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.capman.proto.internal.Common.InternalResponse other) {
        if (other == io.capman.proto.internal.Common.InternalResponse.getDefaultInstance()) return this;
        if (other.hasRet()) {
          setRet(other.getRet());
        }
        if (other.hasRespData()) {
          setRespData(other.getRespData());
        }
        if (other.hasMsg()) {
          bitField0_ |= 0x00000004;
          msg_ = other.msg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRet()) {
          
          return false;
        }
        if (!hasRespData()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.capman.proto.internal.Common.InternalResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.capman.proto.internal.Common.InternalResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int ret_ ;
      /**
       * <code>required int32 ret = 1;</code>
       */
      public boolean hasRet() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 ret = 1;</code>
       */
      public int getRet() {
        return ret_;
      }
      /**
       * <code>required int32 ret = 1;</code>
       */
      public Builder setRet(int value) {
        bitField0_ |= 0x00000001;
        ret_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 ret = 1;</code>
       */
      public Builder clearRet() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ret_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString respData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes respData = 2;</code>
       */
      public boolean hasRespData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes respData = 2;</code>
       */
      public com.google.protobuf.ByteString getRespData() {
        return respData_;
      }
      /**
       * <code>required bytes respData = 2;</code>
       */
      public Builder setRespData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        respData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes respData = 2;</code>
       */
      public Builder clearRespData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        respData_ = getDefaultInstance().getRespData();
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>optional string msg = 3;</code>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string msg = 3;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msg = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msg = 3;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 3;</code>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 3;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        msg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:io.capman.proto.internal.InternalResponse)
    }

    static {
      defaultInstance = new InternalResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:io.capman.proto.internal.InternalResponse)
  }

  public static final int SERVICETYPE_FIELD_NUMBER = 1000;
  /**
   * <code>extend .com.google.protobuf.ServiceOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.ServiceOptions,
      io.capman.proto.internal.Common.EServiceType> serviceType = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        io.capman.proto.internal.Common.EServiceType.class,
        null);
  public static final int DEFAULTSERVICEURIPARAMS_FIELD_NUMBER = 1001;
  /**
   * <code>extend .com.google.protobuf.ServiceOptions { ... }</code>
   *
   * <pre>
   * </pre>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.ServiceOptions,
      java.lang.String> defaultServiceUriParams = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int DEFAULTCLIENTURIPARAMS_FIELD_NUMBER = 1002;
  /**
   * <code>extend .com.google.protobuf.ServiceOptions { ... }</code>
   *
   * <pre>
   * </pre>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.ServiceOptions,
      java.lang.String> defaultClientUriParams = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int DEFAULTCLUSTERSTRATEGY_FIELD_NUMBER = 1000;
  /**
   * <code>extend .com.google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      io.capman.proto.internal.Common.EClusterStrategy> defaultClusterStrategy = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        io.capman.proto.internal.Common.EClusterStrategy.class,
        null);
  public static final int DEFAULTLOADBALANCESTRATEGY_FIELD_NUMBER = 1001;
  /**
   * <code>extend .com.google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      io.capman.proto.internal.Common.ELoadbalanceStrategy> defaultLoadBalanceStrategy = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        io.capman.proto.internal.Common.ELoadbalanceStrategy.class,
        null);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_capman_proto_internal_InternalRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_capman_proto_internal_InternalRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_capman_proto_internal_InternalResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_capman_proto_internal_InternalResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037io/capman/internal/common.proto\022\030io.ca" +
      "pman.proto.internal\032$com/google/protobuf" +
      "/descriptor.proto\"/\n\017InternalRequest\022\013\n\003" +
      "uin\030\001 \002(\003\022\017\n\007reqData\030\002 \002(\014\">\n\020InternalRe" +
      "sponse\022\013\n\003ret\030\001 \002(\005\022\020\n\010respData\030\002 \002(\014\022\013\n" +
      "\003msg\030\003 \001(\t*\225\001\n\017EnumInternalRet\022$\n\027SERIAL" +
      "IZATION_EXCEPTION\020\375\377\377\377\377\377\377\377\377\001\022\036\n\021TIMEOUT_" +
      "EXCEPTION\020\376\377\377\377\377\377\377\377\377\001\022\036\n\021NETWORK_EXCEPTIO" +
      "N\020\377\377\377\377\377\377\377\377\377\001\022\007\n\002OK\020\310\001\022\023\n\016INTERNAL_ERROR\020" +
      "\364\003*V\n\014EServiceType\022\024\n\020EServiceType_Any\020\000",
      "\022\026\n\022EServiceType_Logic\020\001\022\030\n\024EServiceType" +
      "_Storage\020\002*\215\001\n\020EClusterStrategy\022\035\n\031EClus" +
      "terStrategy_FailOver\020\001\022\035\n\031EClusterStrate" +
      "gy_FailFast\020\002\022\036\n\032EClusterStrategy_FailRe" +
      "try\020\003\022\033\n\027EClusterStrategy_Custom\020\004*\246\001\n\024E" +
      "LoadbalanceStrategy\022\'\n#ELoadbalanceStrat" +
      "egy_ConsistentHash\020\001\022\037\n\033ELoadbalanceStra" +
      "tegy_Random\020\002\022#\n\037ELoadbalanceStrategy_Ro" +
      "undRobin\020\003\022\037\n\033ELoadbalanceStrategy_Custo" +
      "m\020\004:s\n\013serviceType\022#.com.google.protobuf",
      ".ServiceOptions\030\350\007 \001(\0162&.io.capman.proto" +
      ".internal.EServiceType:\020EServiceType_Any" +
      ":G\n\027defaultServiceUriParams\022#.com.google" +
      ".protobuf.ServiceOptions\030\351\007 \001(\t:\000:F\n\026def" +
      "aultClientUriParams\022#.com.google.protobu" +
      "f.ServiceOptions\030\352\007 \001(\t:\000:\212\001\n\026defaultClu" +
      "sterStrategy\022\".com.google.protobuf.Metho" +
      "dOptions\030\350\007 \001(\0162*.io.capman.proto.intern" +
      "al.EClusterStrategy:\031EClusterStrategy_Fa" +
      "ilOver:\234\001\n\032defaultLoadBalanceStrategy\022\".",
      "com.google.protobuf.MethodOptions\030\351\007 \001(\016" +
      "2..io.capman.proto.internal.ELoadbalance" +
      "Strategy:#ELoadbalanceStrategy_Consisten" +
      "tHashB\032\n\030io.capman.proto.internal"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
    internal_static_io_capman_proto_internal_InternalRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_capman_proto_internal_InternalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_capman_proto_internal_InternalRequest_descriptor,
        new java.lang.String[] { "Uin", "ReqData", });
    internal_static_io_capman_proto_internal_InternalResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_capman_proto_internal_InternalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_capman_proto_internal_InternalResponse_descriptor,
        new java.lang.String[] { "Ret", "RespData", "Msg", });
    serviceType.internalInit(descriptor.getExtensions().get(0));
    defaultServiceUriParams.internalInit(descriptor.getExtensions().get(1));
    defaultClientUriParams.internalInit(descriptor.getExtensions().get(2));
    defaultClusterStrategy.internalInit(descriptor.getExtensions().get(3));
    defaultLoadBalanceStrategy.internalInit(descriptor.getExtensions().get(4));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
