// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: capman/common.proto

package io.capman.protobuf;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(io.capman.protobuf.Common.appBaseDir);
    registry.add(io.capman.protobuf.Common.appClientModule);
    registry.add(io.capman.protobuf.Common.appProtoModule);
    registry.add(io.capman.protobuf.Common.serviceName);
    registry.add(io.capman.protobuf.Common.serviceType);
    registry.add(io.capman.protobuf.Common.clusterStrategy);
    registry.add(io.capman.protobuf.Common.loadbalanceStrategy);
  }
  /**
   * Protobuf enum {@code capman.EServiceType}
   *
   * <pre>
   *服务类型
   * </pre>
   */
  public enum EServiceType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>EServiceType_Any = 0;</code>
     *
     * <pre>
     *任意
     * </pre>
     */
    EServiceType_Any(0, 0),
    /**
     * <code>EServiceType_Logic = 1;</code>
     *
     * <pre>
     *逻辑服务,默认不会保存状态,例如业务逻辑服务
     * </pre>
     */
    EServiceType_Logic(1, 1),
    /**
     * <code>EServiceType_Storage = 2;</code>
     *
     * <pre>
     *存储服务,用于保存状态,例如各种存储服务,队列服务
     * </pre>
     */
    EServiceType_Storage(2, 2),
    ;

    /**
     * <code>EServiceType_Any = 0;</code>
     *
     * <pre>
     *任意
     * </pre>
     */
    public static final int EServiceType_Any_VALUE = 0;
    /**
     * <code>EServiceType_Logic = 1;</code>
     *
     * <pre>
     *逻辑服务,默认不会保存状态,例如业务逻辑服务
     * </pre>
     */
    public static final int EServiceType_Logic_VALUE = 1;
    /**
     * <code>EServiceType_Storage = 2;</code>
     *
     * <pre>
     *存储服务,用于保存状态,例如各种存储服务,队列服务
     * </pre>
     */
    public static final int EServiceType_Storage_VALUE = 2;


    public final int getNumber() { return value; }

    public static EServiceType valueOf(int value) {
      switch (value) {
        case 0: return EServiceType_Any;
        case 1: return EServiceType_Logic;
        case 2: return EServiceType_Storage;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EServiceType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<EServiceType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EServiceType>() {
            public EServiceType findValueByNumber(int number) {
              return EServiceType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.capman.protobuf.Common.getDescriptor().getEnumTypes().get(0);
    }

    private static final EServiceType[] VALUES = values();

    public static EServiceType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private EServiceType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:capman.EServiceType)
  }

  /**
   * Protobuf enum {@code capman.EClusterStrategy}
   *
   * <pre>
   *方法扩展
   * </pre>
   */
  public enum EClusterStrategy
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>EClusterStrategy_FailOver = 1;</code>
     *
     * <pre>
     *失败自动切换，当出现失败，重试其它服务器，通常用于读操作（推荐使用）
     * </pre>
     */
    EClusterStrategy_FailOver(0, 1),
    /**
     * <code>EClusterStrategy_FailFast = 2;</code>
     *
     * <pre>
     *快速失败，只发起一次调用，失败立即报错,通常用于非幂等性的写操作
     * </pre>
     */
    EClusterStrategy_FailFast(1, 2),
    /**
     * <code>EClusterStrategy_FailRetry = 3;</code>
     *
     * <pre>
     *失败重试，出现网络异常时，直接重试
     * </pre>
     */
    EClusterStrategy_FailRetry(2, 3),
    /**
     * <code>EClusterStrategy_Custom = 4;</code>
     *
     * <pre>
     *自定义
     * </pre>
     */
    EClusterStrategy_Custom(3, 4),
    ;

    /**
     * <code>EClusterStrategy_FailOver = 1;</code>
     *
     * <pre>
     *失败自动切换，当出现失败，重试其它服务器，通常用于读操作（推荐使用）
     * </pre>
     */
    public static final int EClusterStrategy_FailOver_VALUE = 1;
    /**
     * <code>EClusterStrategy_FailFast = 2;</code>
     *
     * <pre>
     *快速失败，只发起一次调用，失败立即报错,通常用于非幂等性的写操作
     * </pre>
     */
    public static final int EClusterStrategy_FailFast_VALUE = 2;
    /**
     * <code>EClusterStrategy_FailRetry = 3;</code>
     *
     * <pre>
     *失败重试，出现网络异常时，直接重试
     * </pre>
     */
    public static final int EClusterStrategy_FailRetry_VALUE = 3;
    /**
     * <code>EClusterStrategy_Custom = 4;</code>
     *
     * <pre>
     *自定义
     * </pre>
     */
    public static final int EClusterStrategy_Custom_VALUE = 4;


    public final int getNumber() { return value; }

    public static EClusterStrategy valueOf(int value) {
      switch (value) {
        case 1: return EClusterStrategy_FailOver;
        case 2: return EClusterStrategy_FailFast;
        case 3: return EClusterStrategy_FailRetry;
        case 4: return EClusterStrategy_Custom;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EClusterStrategy>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<EClusterStrategy>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EClusterStrategy>() {
            public EClusterStrategy findValueByNumber(int number) {
              return EClusterStrategy.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.capman.protobuf.Common.getDescriptor().getEnumTypes().get(1);
    }

    private static final EClusterStrategy[] VALUES = values();

    public static EClusterStrategy valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private EClusterStrategy(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:capman.EClusterStrategy)
  }

  /**
   * Protobuf enum {@code capman.ELoadbalanceStrategy}
   */
  public enum ELoadbalanceStrategy
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ELoadbalanceStrategy_ConsistentHash = 1;</code>
     *
     * <pre>
     *一致性hash
     * </pre>
     */
    ELoadbalanceStrategy_ConsistentHash(0, 1),
    /**
     * <code>ELoadbalanceStrategy_Random = 2;</code>
     *
     * <pre>
     *随机
     * </pre>
     */
    ELoadbalanceStrategy_Random(1, 2),
    /**
     * <code>ELoadbalanceStrategy_RoundRobin = 3;</code>
     *
     * <pre>
     *轮训
     * </pre>
     */
    ELoadbalanceStrategy_RoundRobin(2, 3),
    /**
     * <code>ELoadbalanceStrategy_Custom = 4;</code>
     *
     * <pre>
     *自定义
     * </pre>
     */
    ELoadbalanceStrategy_Custom(3, 4),
    ;

    /**
     * <code>ELoadbalanceStrategy_ConsistentHash = 1;</code>
     *
     * <pre>
     *一致性hash
     * </pre>
     */
    public static final int ELoadbalanceStrategy_ConsistentHash_VALUE = 1;
    /**
     * <code>ELoadbalanceStrategy_Random = 2;</code>
     *
     * <pre>
     *随机
     * </pre>
     */
    public static final int ELoadbalanceStrategy_Random_VALUE = 2;
    /**
     * <code>ELoadbalanceStrategy_RoundRobin = 3;</code>
     *
     * <pre>
     *轮训
     * </pre>
     */
    public static final int ELoadbalanceStrategy_RoundRobin_VALUE = 3;
    /**
     * <code>ELoadbalanceStrategy_Custom = 4;</code>
     *
     * <pre>
     *自定义
     * </pre>
     */
    public static final int ELoadbalanceStrategy_Custom_VALUE = 4;


    public final int getNumber() { return value; }

    public static ELoadbalanceStrategy valueOf(int value) {
      switch (value) {
        case 1: return ELoadbalanceStrategy_ConsistentHash;
        case 2: return ELoadbalanceStrategy_Random;
        case 3: return ELoadbalanceStrategy_RoundRobin;
        case 4: return ELoadbalanceStrategy_Custom;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ELoadbalanceStrategy>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ELoadbalanceStrategy>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ELoadbalanceStrategy>() {
            public ELoadbalanceStrategy findValueByNumber(int number) {
              return ELoadbalanceStrategy.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.capman.protobuf.Common.getDescriptor().getEnumTypes().get(2);
    }

    private static final ELoadbalanceStrategy[] VALUES = values();

    public static ELoadbalanceStrategy valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ELoadbalanceStrategy(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:capman.ELoadbalanceStrategy)
  }

  public interface RequestContextOrBuilder extends
      // @@protoc_insertion_point(interface_extends:capman.RequestContext)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 uin = 1;</code>
     */
    boolean hasUin();
    /**
     * <code>required int32 uin = 1;</code>
     */
    int getUin();
  }
  /**
   * Protobuf type {@code capman.RequestContext}
   */
  public static final class RequestContext extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:capman.RequestContext)
      RequestContextOrBuilder {
    // Use RequestContext.newBuilder() to construct.
    private RequestContext(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RequestContext(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RequestContext defaultInstance;
    public static RequestContext getDefaultInstance() {
      return defaultInstance;
    }

    public RequestContext getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RequestContext(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              uin_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.capman.protobuf.Common.internal_static_capman_RequestContext_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.capman.protobuf.Common.internal_static_capman_RequestContext_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.capman.protobuf.Common.RequestContext.class, io.capman.protobuf.Common.RequestContext.Builder.class);
    }

    public static com.google.protobuf.Parser<RequestContext> PARSER =
        new com.google.protobuf.AbstractParser<RequestContext>() {
      public RequestContext parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestContext(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RequestContext> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int UIN_FIELD_NUMBER = 1;
    private int uin_;
    /**
     * <code>required int32 uin = 1;</code>
     */
    public boolean hasUin() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 uin = 1;</code>
     */
    public int getUin() {
      return uin_;
    }

    private void initFields() {
      uin_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUin()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, uin_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, uin_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static io.capman.protobuf.Common.RequestContext parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.capman.protobuf.Common.RequestContext parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.capman.protobuf.Common.RequestContext parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.capman.protobuf.Common.RequestContext parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.capman.protobuf.Common.RequestContext parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.capman.protobuf.Common.RequestContext parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.capman.protobuf.Common.RequestContext parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.capman.protobuf.Common.RequestContext parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.capman.protobuf.Common.RequestContext parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.capman.protobuf.Common.RequestContext parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.capman.protobuf.Common.RequestContext prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code capman.RequestContext}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:capman.RequestContext)
        io.capman.protobuf.Common.RequestContextOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.capman.protobuf.Common.internal_static_capman_RequestContext_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.capman.protobuf.Common.internal_static_capman_RequestContext_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.capman.protobuf.Common.RequestContext.class, io.capman.protobuf.Common.RequestContext.Builder.class);
      }

      // Construct using io.capman.protobuf.Common.RequestContext.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uin_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.capman.protobuf.Common.internal_static_capman_RequestContext_descriptor;
      }

      public io.capman.protobuf.Common.RequestContext getDefaultInstanceForType() {
        return io.capman.protobuf.Common.RequestContext.getDefaultInstance();
      }

      public io.capman.protobuf.Common.RequestContext build() {
        io.capman.protobuf.Common.RequestContext result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.capman.protobuf.Common.RequestContext buildPartial() {
        io.capman.protobuf.Common.RequestContext result = new io.capman.protobuf.Common.RequestContext(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uin_ = uin_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.capman.protobuf.Common.RequestContext) {
          return mergeFrom((io.capman.protobuf.Common.RequestContext)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.capman.protobuf.Common.RequestContext other) {
        if (other == io.capman.protobuf.Common.RequestContext.getDefaultInstance()) return this;
        if (other.hasUin()) {
          setUin(other.getUin());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUin()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.capman.protobuf.Common.RequestContext parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.capman.protobuf.Common.RequestContext) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int uin_ ;
      /**
       * <code>required int32 uin = 1;</code>
       */
      public boolean hasUin() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 uin = 1;</code>
       */
      public int getUin() {
        return uin_;
      }
      /**
       * <code>required int32 uin = 1;</code>
       */
      public Builder setUin(int value) {
        bitField0_ |= 0x00000001;
        uin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 uin = 1;</code>
       */
      public Builder clearUin() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uin_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:capman.RequestContext)
    }

    static {
      defaultInstance = new RequestContext(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:capman.RequestContext)
  }

  public interface AppConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:capman.AppConfig)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code capman.AppConfig}
   */
  public static final class AppConfig extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:capman.AppConfig)
      AppConfigOrBuilder {
    // Use AppConfig.newBuilder() to construct.
    private AppConfig(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AppConfig(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AppConfig defaultInstance;
    public static AppConfig getDefaultInstance() {
      return defaultInstance;
    }

    public AppConfig getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AppConfig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.capman.protobuf.Common.internal_static_capman_AppConfig_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.capman.protobuf.Common.internal_static_capman_AppConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.capman.protobuf.Common.AppConfig.class, io.capman.protobuf.Common.AppConfig.Builder.class);
    }

    public static com.google.protobuf.Parser<AppConfig> PARSER =
        new com.google.protobuf.AbstractParser<AppConfig>() {
      public AppConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AppConfig(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AppConfig> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static io.capman.protobuf.Common.AppConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.capman.protobuf.Common.AppConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.capman.protobuf.Common.AppConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.capman.protobuf.Common.AppConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.capman.protobuf.Common.AppConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.capman.protobuf.Common.AppConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.capman.protobuf.Common.AppConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.capman.protobuf.Common.AppConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.capman.protobuf.Common.AppConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.capman.protobuf.Common.AppConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.capman.protobuf.Common.AppConfig prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code capman.AppConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:capman.AppConfig)
        io.capman.protobuf.Common.AppConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.capman.protobuf.Common.internal_static_capman_AppConfig_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.capman.protobuf.Common.internal_static_capman_AppConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.capman.protobuf.Common.AppConfig.class, io.capman.protobuf.Common.AppConfig.Builder.class);
      }

      // Construct using io.capman.protobuf.Common.AppConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.capman.protobuf.Common.internal_static_capman_AppConfig_descriptor;
      }

      public io.capman.protobuf.Common.AppConfig getDefaultInstanceForType() {
        return io.capman.protobuf.Common.AppConfig.getDefaultInstance();
      }

      public io.capman.protobuf.Common.AppConfig build() {
        io.capman.protobuf.Common.AppConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.capman.protobuf.Common.AppConfig buildPartial() {
        io.capman.protobuf.Common.AppConfig result = new io.capman.protobuf.Common.AppConfig(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.capman.protobuf.Common.AppConfig) {
          return mergeFrom((io.capman.protobuf.Common.AppConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.capman.protobuf.Common.AppConfig other) {
        if (other == io.capman.protobuf.Common.AppConfig.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.capman.protobuf.Common.AppConfig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.capman.protobuf.Common.AppConfig) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:capman.AppConfig)
    }

    static {
      defaultInstance = new AppConfig(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:capman.AppConfig)
  }

  public static final int APP_BASE_DIR_FIELD_NUMBER = 10000;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.String> appBaseDir = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int APP_CLIENT_MODULE_FIELD_NUMBER = 10002;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   *
   * <pre>
   *    optional string app_module = 10001 [default="${app_base_dir}/${project}-${protofilename}"];
   * </pre>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.String> appClientModule = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int APP_PROTO_MODULE_FIELD_NUMBER = 10003;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.String> appProtoModule = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int SERVICE_NAME_FIELD_NUMBER = 10000;
  /**
   * <code>extend .google.protobuf.ServiceOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.ServiceOptions,
      java.lang.String> serviceName = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int SERVICE_TYPE_FIELD_NUMBER = 10001;
  /**
   * <code>extend .google.protobuf.ServiceOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.ServiceOptions,
      java.lang.Integer> serviceType = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  public static final int CLUSTER_STRATEGY_FIELD_NUMBER = 10000;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      io.capman.protobuf.Common.EClusterStrategy> clusterStrategy = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        io.capman.protobuf.Common.EClusterStrategy.class,
        null);
  public static final int LOADBALANCE_STRATEGY_FIELD_NUMBER = 10001;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      io.capman.protobuf.Common.ELoadbalanceStrategy> loadbalanceStrategy = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        io.capman.protobuf.Common.ELoadbalanceStrategy.class,
        null);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_capman_RequestContext_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_capman_RequestContext_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_capman_AppConfig_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_capman_AppConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023capman/common.proto\022\006capman\032 google/pr" +
      "otobuf/descriptor.proto\"\035\n\016RequestContex" +
      "t\022\013\n\003uin\030\001 \002(\005\"\013\n\tAppConfig*V\n\014EServiceT" +
      "ype\022\024\n\020EServiceType_Any\020\000\022\026\n\022EServiceTyp" +
      "e_Logic\020\001\022\030\n\024EServiceType_Storage\020\002*\215\001\n\020" +
      "EClusterStrategy\022\035\n\031EClusterStrategy_Fai" +
      "lOver\020\001\022\035\n\031EClusterStrategy_FailFast\020\002\022\036" +
      "\n\032EClusterStrategy_FailRetry\020\003\022\033\n\027EClust" +
      "erStrategy_Custom\020\004*\246\001\n\024ELoadbalanceStra" +
      "tegy\022\'\n#ELoadbalanceStrategy_ConsistentH",
      "ash\020\001\022\037\n\033ELoadbalanceStrategy_Random\020\002\022#" +
      "\n\037ELoadbalanceStrategy_RoundRobin\020\003\022\037\n\033E" +
      "LoadbalanceStrategy_Custom\020\004:F\n\014app_base" +
      "_dir\022\034.google.protobuf.FileOptions\030\220N \001(" +
      "\t:\021../../${project}/:[\n\021app_client_modul" +
      "e\022\034.google.protobuf.FileOptions\030\222N \001(\t:!" +
      "${app_base_dir}/${project}-client:Y\n\020app" +
      "_proto_module\022\034.google.protobuf.FileOpti" +
      "ons\030\223N \001(\t: ${app_base_dir}/${project}-p" +
      "roto:8\n\014service_name\022\037.google.protobuf.S",
      "erviceOptions\030\220N \001(\t:\000:9\n\014service_type\022\037" +
      ".google.protobuf.ServiceOptions\030\221N \001(\005:\001" +
      "0:n\n\020cluster_strategy\022\036.google.protobuf." +
      "MethodOptions\030\220N \001(\0162\030.capman.EClusterSt" +
      "rategy:\031EClusterStrategy_FailOver:\200\001\n\024lo" +
      "adbalance_strategy\022\036.google.protobuf.Met" +
      "hodOptions\030\221N \001(\0162\034.capman.ELoadbalanceS" +
      "trategy:#ELoadbalanceStrategy_Consistent" +
      "HashB\024\n\022io.capman.protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
    internal_static_capman_RequestContext_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_capman_RequestContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_capman_RequestContext_descriptor,
        new java.lang.String[] { "Uin", });
    internal_static_capman_AppConfig_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_capman_AppConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_capman_AppConfig_descriptor,
        new java.lang.String[] { });
    appBaseDir.internalInit(descriptor.getExtensions().get(0));
    appClientModule.internalInit(descriptor.getExtensions().get(1));
    appProtoModule.internalInit(descriptor.getExtensions().get(2));
    serviceName.internalInit(descriptor.getExtensions().get(3));
    serviceType.internalInit(descriptor.getExtensions().get(4));
    clusterStrategy.internalInit(descriptor.getExtensions().get(5));
    loadbalanceStrategy.internalInit(descriptor.getExtensions().get(6));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
