// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: capman/internal.proto

package io.capman.protobuf;

public final class Internal {
  private Internal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code capman.EnumInternalRet}
   */
  public enum EnumInternalRet
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>EnumInternalRet_INTERNAL_ERROR = -6;</code>
     */
    EnumInternalRet_INTERNAL_ERROR(0, -6),
    /**
     * <code>EnumInternalRet_METHOD_NOT_FOUND = -5;</code>
     */
    EnumInternalRet_METHOD_NOT_FOUND(1, -5),
    /**
     * <code>EnumInternalRet_PARAMETER_EXCEPTION = -4;</code>
     */
    EnumInternalRet_PARAMETER_EXCEPTION(2, -4),
    /**
     * <code>EnumInternalRet_TIMEOUT_EXCEPTION = -3;</code>
     */
    EnumInternalRet_TIMEOUT_EXCEPTION(3, -3),
    /**
     * <code>EnumInternalRet_NETWORK_EXCEPTION = -2;</code>
     */
    EnumInternalRet_NETWORK_EXCEPTION(4, -2),
    /**
     * <code>EnumInternalRet_BIZ_ERROR = -1;</code>
     */
    EnumInternalRet_BIZ_ERROR(5, -1),
    /**
     * <code>EnumInternalRet_OK = 0;</code>
     */
    EnumInternalRet_OK(6, 0),
    ;

    /**
     * <code>EnumInternalRet_INTERNAL_ERROR = -6;</code>
     */
    public static final int EnumInternalRet_INTERNAL_ERROR_VALUE = -6;
    /**
     * <code>EnumInternalRet_METHOD_NOT_FOUND = -5;</code>
     */
    public static final int EnumInternalRet_METHOD_NOT_FOUND_VALUE = -5;
    /**
     * <code>EnumInternalRet_PARAMETER_EXCEPTION = -4;</code>
     */
    public static final int EnumInternalRet_PARAMETER_EXCEPTION_VALUE = -4;
    /**
     * <code>EnumInternalRet_TIMEOUT_EXCEPTION = -3;</code>
     */
    public static final int EnumInternalRet_TIMEOUT_EXCEPTION_VALUE = -3;
    /**
     * <code>EnumInternalRet_NETWORK_EXCEPTION = -2;</code>
     */
    public static final int EnumInternalRet_NETWORK_EXCEPTION_VALUE = -2;
    /**
     * <code>EnumInternalRet_BIZ_ERROR = -1;</code>
     */
    public static final int EnumInternalRet_BIZ_ERROR_VALUE = -1;
    /**
     * <code>EnumInternalRet_OK = 0;</code>
     */
    public static final int EnumInternalRet_OK_VALUE = 0;


    public final int getNumber() { return value; }

    public static EnumInternalRet valueOf(int value) {
      switch (value) {
        case -6: return EnumInternalRet_INTERNAL_ERROR;
        case -5: return EnumInternalRet_METHOD_NOT_FOUND;
        case -4: return EnumInternalRet_PARAMETER_EXCEPTION;
        case -3: return EnumInternalRet_TIMEOUT_EXCEPTION;
        case -2: return EnumInternalRet_NETWORK_EXCEPTION;
        case -1: return EnumInternalRet_BIZ_ERROR;
        case 0: return EnumInternalRet_OK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EnumInternalRet>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<EnumInternalRet>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EnumInternalRet>() {
            public EnumInternalRet findValueByNumber(int number) {
              return EnumInternalRet.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.capman.protobuf.Internal.getDescriptor().getEnumTypes().get(0);
    }

    private static final EnumInternalRet[] VALUES = values();

    public static EnumInternalRet valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private EnumInternalRet(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:capman.EnumInternalRet)
  }

  public interface InternalRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:capman.InternalRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 uin = 1;</code>
     */
    boolean hasUin();
    /**
     * <code>required int32 uin = 1;</code>
     */
    int getUin();

    /**
     * <code>required string method = 2;</code>
     */
    boolean hasMethod();
    /**
     * <code>required string method = 2;</code>
     */
    java.lang.String getMethod();
    /**
     * <code>required string method = 2;</code>
     */
    com.google.protobuf.ByteString
        getMethodBytes();

    /**
     * <code>required bytes reqData = 3;</code>
     */
    boolean hasReqData();
    /**
     * <code>required bytes reqData = 3;</code>
     */
    com.google.protobuf.ByteString getReqData();
  }
  /**
   * Protobuf type {@code capman.InternalRequest}
   */
  public static final class InternalRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:capman.InternalRequest)
      InternalRequestOrBuilder {
    // Use InternalRequest.newBuilder() to construct.
    private InternalRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private InternalRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final InternalRequest defaultInstance;
    public static InternalRequest getDefaultInstance() {
      return defaultInstance;
    }

    public InternalRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private InternalRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              uin_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              method_ = bs;
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              reqData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.capman.protobuf.Internal.internal_static_capman_InternalRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.capman.protobuf.Internal.internal_static_capman_InternalRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.capman.protobuf.Internal.InternalRequest.class, io.capman.protobuf.Internal.InternalRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<InternalRequest> PARSER =
        new com.google.protobuf.AbstractParser<InternalRequest>() {
      public InternalRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InternalRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<InternalRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int UIN_FIELD_NUMBER = 1;
    private int uin_;
    /**
     * <code>required int32 uin = 1;</code>
     */
    public boolean hasUin() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 uin = 1;</code>
     */
    public int getUin() {
      return uin_;
    }

    public static final int METHOD_FIELD_NUMBER = 2;
    private java.lang.Object method_;
    /**
     * <code>required string method = 2;</code>
     */
    public boolean hasMethod() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string method = 2;</code>
     */
    public java.lang.String getMethod() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          method_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string method = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMethodBytes() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQDATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString reqData_;
    /**
     * <code>required bytes reqData = 3;</code>
     */
    public boolean hasReqData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes reqData = 3;</code>
     */
    public com.google.protobuf.ByteString getReqData() {
      return reqData_;
    }

    private void initFields() {
      uin_ = 0;
      method_ = "";
      reqData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUin()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMethod()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReqData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, uin_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMethodBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, reqData_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, uin_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMethodBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, reqData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static io.capman.protobuf.Internal.InternalRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.capman.protobuf.Internal.InternalRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.capman.protobuf.Internal.InternalRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.capman.protobuf.Internal.InternalRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.capman.protobuf.Internal.InternalRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.capman.protobuf.Internal.InternalRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.capman.protobuf.Internal.InternalRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.capman.protobuf.Internal.InternalRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.capman.protobuf.Internal.InternalRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.capman.protobuf.Internal.InternalRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.capman.protobuf.Internal.InternalRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code capman.InternalRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:capman.InternalRequest)
        io.capman.protobuf.Internal.InternalRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.capman.protobuf.Internal.internal_static_capman_InternalRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.capman.protobuf.Internal.internal_static_capman_InternalRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.capman.protobuf.Internal.InternalRequest.class, io.capman.protobuf.Internal.InternalRequest.Builder.class);
      }

      // Construct using io.capman.protobuf.Internal.InternalRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uin_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        method_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        reqData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.capman.protobuf.Internal.internal_static_capman_InternalRequest_descriptor;
      }

      public io.capman.protobuf.Internal.InternalRequest getDefaultInstanceForType() {
        return io.capman.protobuf.Internal.InternalRequest.getDefaultInstance();
      }

      public io.capman.protobuf.Internal.InternalRequest build() {
        io.capman.protobuf.Internal.InternalRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.capman.protobuf.Internal.InternalRequest buildPartial() {
        io.capman.protobuf.Internal.InternalRequest result = new io.capman.protobuf.Internal.InternalRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uin_ = uin_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.method_ = method_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.reqData_ = reqData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.capman.protobuf.Internal.InternalRequest) {
          return mergeFrom((io.capman.protobuf.Internal.InternalRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.capman.protobuf.Internal.InternalRequest other) {
        if (other == io.capman.protobuf.Internal.InternalRequest.getDefaultInstance()) return this;
        if (other.hasUin()) {
          setUin(other.getUin());
        }
        if (other.hasMethod()) {
          bitField0_ |= 0x00000002;
          method_ = other.method_;
          onChanged();
        }
        if (other.hasReqData()) {
          setReqData(other.getReqData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUin()) {
          
          return false;
        }
        if (!hasMethod()) {
          
          return false;
        }
        if (!hasReqData()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.capman.protobuf.Internal.InternalRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.capman.protobuf.Internal.InternalRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int uin_ ;
      /**
       * <code>required int32 uin = 1;</code>
       */
      public boolean hasUin() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 uin = 1;</code>
       */
      public int getUin() {
        return uin_;
      }
      /**
       * <code>required int32 uin = 1;</code>
       */
      public Builder setUin(int value) {
        bitField0_ |= 0x00000001;
        uin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 uin = 1;</code>
       */
      public Builder clearUin() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uin_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object method_ = "";
      /**
       * <code>required string method = 2;</code>
       */
      public boolean hasMethod() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string method = 2;</code>
       */
      public java.lang.String getMethod() {
        java.lang.Object ref = method_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            method_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string method = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMethodBytes() {
        java.lang.Object ref = method_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          method_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string method = 2;</code>
       */
      public Builder setMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string method = 2;</code>
       */
      public Builder clearMethod() {
        bitField0_ = (bitField0_ & ~0x00000002);
        method_ = getDefaultInstance().getMethod();
        onChanged();
        return this;
      }
      /**
       * <code>required string method = 2;</code>
       */
      public Builder setMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        method_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString reqData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes reqData = 3;</code>
       */
      public boolean hasReqData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes reqData = 3;</code>
       */
      public com.google.protobuf.ByteString getReqData() {
        return reqData_;
      }
      /**
       * <code>required bytes reqData = 3;</code>
       */
      public Builder setReqData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        reqData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes reqData = 3;</code>
       */
      public Builder clearReqData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        reqData_ = getDefaultInstance().getReqData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:capman.InternalRequest)
    }

    static {
      defaultInstance = new InternalRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:capman.InternalRequest)
  }

  public interface InternalResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:capman.InternalResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 ret = 1;</code>
     */
    boolean hasRet();
    /**
     * <code>required int32 ret = 1;</code>
     */
    int getRet();

    /**
     * <code>required bytes respData = 2;</code>
     */
    boolean hasRespData();
    /**
     * <code>required bytes respData = 2;</code>
     */
    com.google.protobuf.ByteString getRespData();

    /**
     * <code>optional string msg = 3;</code>
     */
    boolean hasMsg();
    /**
     * <code>optional string msg = 3;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>optional string msg = 3;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * Protobuf type {@code capman.InternalResponse}
   */
  public static final class InternalResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:capman.InternalResponse)
      InternalResponseOrBuilder {
    // Use InternalResponse.newBuilder() to construct.
    private InternalResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private InternalResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final InternalResponse defaultInstance;
    public static InternalResponse getDefaultInstance() {
      return defaultInstance;
    }

    public InternalResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private InternalResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              ret_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              respData_ = input.readBytes();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              msg_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.capman.protobuf.Internal.internal_static_capman_InternalResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.capman.protobuf.Internal.internal_static_capman_InternalResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.capman.protobuf.Internal.InternalResponse.class, io.capman.protobuf.Internal.InternalResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<InternalResponse> PARSER =
        new com.google.protobuf.AbstractParser<InternalResponse>() {
      public InternalResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InternalResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<InternalResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RET_FIELD_NUMBER = 1;
    private int ret_;
    /**
     * <code>required int32 ret = 1;</code>
     */
    public boolean hasRet() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 ret = 1;</code>
     */
    public int getRet() {
      return ret_;
    }

    public static final int RESPDATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString respData_;
    /**
     * <code>required bytes respData = 2;</code>
     */
    public boolean hasRespData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes respData = 2;</code>
     */
    public com.google.protobuf.ByteString getRespData() {
      return respData_;
    }

    public static final int MSG_FIELD_NUMBER = 3;
    private java.lang.Object msg_;
    /**
     * <code>optional string msg = 3;</code>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string msg = 3;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msg = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      ret_ = 0;
      respData_ = com.google.protobuf.ByteString.EMPTY;
      msg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRet()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRespData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, ret_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, respData_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, ret_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, respData_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static io.capman.protobuf.Internal.InternalResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.capman.protobuf.Internal.InternalResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.capman.protobuf.Internal.InternalResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.capman.protobuf.Internal.InternalResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.capman.protobuf.Internal.InternalResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.capman.protobuf.Internal.InternalResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.capman.protobuf.Internal.InternalResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.capman.protobuf.Internal.InternalResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.capman.protobuf.Internal.InternalResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.capman.protobuf.Internal.InternalResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.capman.protobuf.Internal.InternalResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code capman.InternalResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:capman.InternalResponse)
        io.capman.protobuf.Internal.InternalResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.capman.protobuf.Internal.internal_static_capman_InternalResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.capman.protobuf.Internal.internal_static_capman_InternalResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.capman.protobuf.Internal.InternalResponse.class, io.capman.protobuf.Internal.InternalResponse.Builder.class);
      }

      // Construct using io.capman.protobuf.Internal.InternalResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ret_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        respData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.capman.protobuf.Internal.internal_static_capman_InternalResponse_descriptor;
      }

      public io.capman.protobuf.Internal.InternalResponse getDefaultInstanceForType() {
        return io.capman.protobuf.Internal.InternalResponse.getDefaultInstance();
      }

      public io.capman.protobuf.Internal.InternalResponse build() {
        io.capman.protobuf.Internal.InternalResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.capman.protobuf.Internal.InternalResponse buildPartial() {
        io.capman.protobuf.Internal.InternalResponse result = new io.capman.protobuf.Internal.InternalResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ret_ = ret_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.respData_ = respData_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.msg_ = msg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.capman.protobuf.Internal.InternalResponse) {
          return mergeFrom((io.capman.protobuf.Internal.InternalResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.capman.protobuf.Internal.InternalResponse other) {
        if (other == io.capman.protobuf.Internal.InternalResponse.getDefaultInstance()) return this;
        if (other.hasRet()) {
          setRet(other.getRet());
        }
        if (other.hasRespData()) {
          setRespData(other.getRespData());
        }
        if (other.hasMsg()) {
          bitField0_ |= 0x00000004;
          msg_ = other.msg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRet()) {
          
          return false;
        }
        if (!hasRespData()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.capman.protobuf.Internal.InternalResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.capman.protobuf.Internal.InternalResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int ret_ ;
      /**
       * <code>required int32 ret = 1;</code>
       */
      public boolean hasRet() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 ret = 1;</code>
       */
      public int getRet() {
        return ret_;
      }
      /**
       * <code>required int32 ret = 1;</code>
       */
      public Builder setRet(int value) {
        bitField0_ |= 0x00000001;
        ret_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 ret = 1;</code>
       */
      public Builder clearRet() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ret_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString respData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes respData = 2;</code>
       */
      public boolean hasRespData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes respData = 2;</code>
       */
      public com.google.protobuf.ByteString getRespData() {
        return respData_;
      }
      /**
       * <code>required bytes respData = 2;</code>
       */
      public Builder setRespData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        respData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes respData = 2;</code>
       */
      public Builder clearRespData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        respData_ = getDefaultInstance().getRespData();
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>optional string msg = 3;</code>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string msg = 3;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msg = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msg = 3;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 3;</code>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 3;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        msg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:capman.InternalResponse)
    }

    static {
      defaultInstance = new InternalResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:capman.InternalResponse)
  }

  public interface TestMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:capman.TestMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 f1 = 1;</code>
     */
    boolean hasF1();
    /**
     * <code>required int32 f1 = 1;</code>
     */
    int getF1();

    /**
     * <code>required string f2 = 2;</code>
     */
    boolean hasF2();
    /**
     * <code>required string f2 = 2;</code>
     */
    java.lang.String getF2();
    /**
     * <code>required string f2 = 2;</code>
     */
    com.google.protobuf.ByteString
        getF2Bytes();
  }
  /**
   * Protobuf type {@code capman.TestMessage}
   */
  public static final class TestMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:capman.TestMessage)
      TestMessageOrBuilder {
    // Use TestMessage.newBuilder() to construct.
    private TestMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TestMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TestMessage defaultInstance;
    public static TestMessage getDefaultInstance() {
      return defaultInstance;
    }

    public TestMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TestMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              f1_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              f2_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.capman.protobuf.Internal.internal_static_capman_TestMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.capman.protobuf.Internal.internal_static_capman_TestMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.capman.protobuf.Internal.TestMessage.class, io.capman.protobuf.Internal.TestMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<TestMessage> PARSER =
        new com.google.protobuf.AbstractParser<TestMessage>() {
      public TestMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TestMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int F1_FIELD_NUMBER = 1;
    private int f1_;
    /**
     * <code>required int32 f1 = 1;</code>
     */
    public boolean hasF1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 f1 = 1;</code>
     */
    public int getF1() {
      return f1_;
    }

    public static final int F2_FIELD_NUMBER = 2;
    private java.lang.Object f2_;
    /**
     * <code>required string f2 = 2;</code>
     */
    public boolean hasF2() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string f2 = 2;</code>
     */
    public java.lang.String getF2() {
      java.lang.Object ref = f2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          f2_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string f2 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getF2Bytes() {
      java.lang.Object ref = f2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        f2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      f1_ = 0;
      f2_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasF1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasF2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, f1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getF2Bytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, f1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getF2Bytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static io.capman.protobuf.Internal.TestMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.capman.protobuf.Internal.TestMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.capman.protobuf.Internal.TestMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.capman.protobuf.Internal.TestMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.capman.protobuf.Internal.TestMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.capman.protobuf.Internal.TestMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.capman.protobuf.Internal.TestMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.capman.protobuf.Internal.TestMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.capman.protobuf.Internal.TestMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.capman.protobuf.Internal.TestMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.capman.protobuf.Internal.TestMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code capman.TestMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:capman.TestMessage)
        io.capman.protobuf.Internal.TestMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.capman.protobuf.Internal.internal_static_capman_TestMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.capman.protobuf.Internal.internal_static_capman_TestMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.capman.protobuf.Internal.TestMessage.class, io.capman.protobuf.Internal.TestMessage.Builder.class);
      }

      // Construct using io.capman.protobuf.Internal.TestMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        f1_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        f2_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.capman.protobuf.Internal.internal_static_capman_TestMessage_descriptor;
      }

      public io.capman.protobuf.Internal.TestMessage getDefaultInstanceForType() {
        return io.capman.protobuf.Internal.TestMessage.getDefaultInstance();
      }

      public io.capman.protobuf.Internal.TestMessage build() {
        io.capman.protobuf.Internal.TestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.capman.protobuf.Internal.TestMessage buildPartial() {
        io.capman.protobuf.Internal.TestMessage result = new io.capman.protobuf.Internal.TestMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.f1_ = f1_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.f2_ = f2_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.capman.protobuf.Internal.TestMessage) {
          return mergeFrom((io.capman.protobuf.Internal.TestMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.capman.protobuf.Internal.TestMessage other) {
        if (other == io.capman.protobuf.Internal.TestMessage.getDefaultInstance()) return this;
        if (other.hasF1()) {
          setF1(other.getF1());
        }
        if (other.hasF2()) {
          bitField0_ |= 0x00000002;
          f2_ = other.f2_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasF1()) {
          
          return false;
        }
        if (!hasF2()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.capman.protobuf.Internal.TestMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.capman.protobuf.Internal.TestMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int f1_ ;
      /**
       * <code>required int32 f1 = 1;</code>
       */
      public boolean hasF1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 f1 = 1;</code>
       */
      public int getF1() {
        return f1_;
      }
      /**
       * <code>required int32 f1 = 1;</code>
       */
      public Builder setF1(int value) {
        bitField0_ |= 0x00000001;
        f1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 f1 = 1;</code>
       */
      public Builder clearF1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        f1_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object f2_ = "";
      /**
       * <code>required string f2 = 2;</code>
       */
      public boolean hasF2() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string f2 = 2;</code>
       */
      public java.lang.String getF2() {
        java.lang.Object ref = f2_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            f2_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string f2 = 2;</code>
       */
      public com.google.protobuf.ByteString
          getF2Bytes() {
        java.lang.Object ref = f2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          f2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string f2 = 2;</code>
       */
      public Builder setF2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        f2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string f2 = 2;</code>
       */
      public Builder clearF2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        f2_ = getDefaultInstance().getF2();
        onChanged();
        return this;
      }
      /**
       * <code>required string f2 = 2;</code>
       */
      public Builder setF2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        f2_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:capman.TestMessage)
    }

    static {
      defaultInstance = new TestMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:capman.TestMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_capman_InternalRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_capman_InternalRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_capman_InternalResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_capman_InternalResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_capman_TestMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_capman_TestMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025capman/internal.proto\022\006capman\"?\n\017Inter" +
      "nalRequest\022\013\n\003uin\030\001 \002(\005\022\016\n\006method\030\002 \002(\t\022" +
      "\017\n\007reqData\030\003 \002(\014\">\n\020InternalResponse\022\013\n\003" +
      "ret\030\001 \002(\005\022\020\n\010respData\030\002 \002(\014\022\013\n\003msg\030\003 \001(\t" +
      "\"%\n\013TestMessage\022\n\n\002f1\030\001 \002(\005\022\n\n\002f2\030\002 \002(\t*" +
      "\277\002\n\017EnumInternalRet\022+\n\036EnumInternalRet_I" +
      "NTERNAL_ERROR\020\372\377\377\377\377\377\377\377\377\001\022-\n EnumInternal" +
      "Ret_METHOD_NOT_FOUND\020\373\377\377\377\377\377\377\377\377\001\0220\n#EnumI" +
      "nternalRet_PARAMETER_EXCEPTION\020\374\377\377\377\377\377\377\377\377" +
      "\001\022.\n!EnumInternalRet_TIMEOUT_EXCEPTION\020\375",
      "\377\377\377\377\377\377\377\377\001\022.\n!EnumInternalRet_NETWORK_EXC" +
      "EPTION\020\376\377\377\377\377\377\377\377\377\001\022&\n\031EnumInternalRet_BIZ" +
      "_ERROR\020\377\377\377\377\377\377\377\377\377\001\022\026\n\022EnumInternalRet_OK\020" +
      "\000B\026\n\022io.capman.protobufH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_capman_InternalRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_capman_InternalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_capman_InternalRequest_descriptor,
        new java.lang.String[] { "Uin", "Method", "ReqData", });
    internal_static_capman_InternalResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_capman_InternalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_capman_InternalResponse_descriptor,
        new java.lang.String[] { "Ret", "RespData", "Msg", });
    internal_static_capman_TestMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_capman_TestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_capman_TestMessage_descriptor,
        new java.lang.String[] { "F1", "F2", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
